### ISSUE TITLE
Web5-kt and tbdex-kt deprecation tracking checklist

### ISSUE THREAD

**Issue by nitro-neal** [TBD54566975/web5-rs#315]
web5-kt and tbdex-kt depreciation checklist in lieu of web5-core-kt and tbdex-core-kt

#### `web5-core-kt`
- [x] **Feature Parity**
  - [x] Credential Schema
  - [x] Credential Status List
  - [x] Evidence Field
  - [x] PEX
    - [x] select_credentials
    - [x] create_presentation_from_credentials
    - [x] verifiable presentation
- [x] **Windows build**
- [x] **Decouple `Web5Exception` from UniFFI codegen**
- [x] secp256k1 verification support
- [x] **Pass over old SDK for feature completeness sanity check**
- [x] **README updates**
- [x] **In-line code documentation**
  - [x] **dokka kt docs**
- [x] **Artifact publishing**
- [x] **FOSSA Scanning**
  - [x] License
  - [x] Security
- [x] **CodeCov (test coverage)**
- [x] ** BUGS
  - [x] fix [[XMLSCHEMA11-2](https://www.w3.org/TR/xmlschema11-2/#dateTime)] dates

#### `tbdex-core-kt`
- [x] **Feature Parity**
- [x] **Test Vectors**
- [x] **Windows build**
- [x] **Pass over old SDK for feature completeness sanity check**
- [x] **Remove `web5` shim**
  - [x] Add standard `TbdexError`
  - [x] Totally decouple from UniFFI code-gen
- [x] **README updates**
- [x] **In-line code documentation**
  - [x] **dokka kt docs**
- [x] **Artifact publishing**
- [x] **FOSSA Scanning**
  - [x] License
  - [x] Security
- [ ] **Cut new release using new web5-kt release**

#### Ongoing and Followups:
- [ ] **Web5 Remaining Test Vectors**
- [ ] **Web5 CodeQL (Static analysis)**
- [ ] **Tbdex CodeCov (test coverage)**
- [ ] **Tbdex CodeQL (Static analysis)**

**Comment by KendallWeihe** [comment]
web5 windows build completed in #329

**Comment by KendallWeihe** [comment]
VC evidence completed in #331 

VC credential schema completed in #332

**Comment by KendallWeihe** [comment]
Status list creds completed in #320

**Comment by KendallWeihe** [comment]
Decouple `Web5Exception` completed in #334

**Comment by KendallWeihe** [comment]
tbdex windows build complete here https://github.com/TBD54566975/tbdex-rs/pull/114

**Comment by KendallWeihe** [comment]
remove web5 shim completed here https://github.com/TBD54566975/tbdex-rs/pull/115

decouple from uniffi code gen here https://github.com/TBD54566975/tbdex-rs/pull/116

**Comment by KendallWeihe** [comment]
standard `TbdexError` added here https://github.com/TBD54566975/tbdex-rs/pull/117

**Comment by KendallWeihe** [comment]
datetime fix in #343

**Comment by KendallWeihe** [comment]
create_presentation_from_credentials completed in #347 

secp256k1 completed in #350
