### ISSUE TITLE
(Feature): Add ability to pass in additional-properties in Web5 CLI to `web5 vc create`

### ISSUE THREAD

**Issue by blackgirlbytes** [TBD54566975/web5-rs#326]
## 🚀 Goal
Enhance the `web5 vc create` command to allow users to pass in additional properties when creating a Verifiable Credential.

## 🔑 Tasks
- [ ] Modify the `web5 vc create` command to accept additional properties
Example below:
```bash
web5 vc create rizel \
  --portable-did $PORTABLE_DID \
  --issuer "did:dht:pe45oj88hq9zza3cjd41r5rej9ekfg9bq7k4jjeaw889t78jesko" \
  --expiration-date "2025-12-31T23:59:59Z" \
  --additional-property "role:engineer" \
  --additional-property "clearance:level5"
```
- [ ] Determine the best format for passing additional properties (e.g., JSON string, key-value pairs)
- [ ] Implement the logic to incorporate these additional properties into the created VC
- [ ] Add appropriate error handling for invalid additional properties
- [ ] Update the CLI documentation to explain how to use this new feature
- [ ] Add examples demonstrating the use of additional properties
- [ ] Write tests to ensure the feature works as expected

## 🌟 Resources
- [Current Web5 Rust CLI Documentation](https://github.com/TBD54566975/web5-rs/tree/main/crates/web5_cli)
- [Web5 documentation on Creating VC](https://developer.tbd.website/docs/web5/verifiable-credentials/vc-issuance)
- [Verifiable Credentials Data Model](https://www.w3.org/TR/vc-data-model/)
- [Web5 CLI built in Go for reference](https://github.com/TBD54566975/web5-go/tree/main/cmd/web5)

## Getting Started
1. Comment ".take" on this issue to get assigned
2. Fork the repository and create a new branch for this task
3. Implement the feature as described in the tasks
4. Submit a pull request with your changes
5. Respond to any feedback during the review process

## 💭 Questions?
If you have any questions or need clarification, please comment on this issue or join our [Discord](https://discord.gg/tbd) community.
Happy coding! 🎉

**Comment by aruokhai** [comment]
Taking this :)

**Comment by aruokhai** [comment]
For the First task, i thought about the first approach but it seams to requires lots of typing which increases the chances for errors. Nevertheless, its ease of use is much appreciated when compared to a config file, which has a requirement of passing a correct file path, but can improve the speed of passing lots of additional parameters. 

Therefore i have settled on an approach that makes use of the best of both worlds:
``` bash
web5 vc create rizel \
  --portable-did $PORTABLE_DID \
  --issuer "did:dht:pe45oj88hq9zza3cjd41r5rej9ekfg9bq7k4jjeaw889t78jesko" \
  --expiration-date "2025-12-31T23:59:59Z" \
  --x-role "engineer" \
  --x-clearance "level5"
  --x "./path-to-env"
````

**Precedence**:  _Key-Value_ > _Env File_

**Comment by blackgirlbytes** [comment]
Hi @aruokhai,

Your initial `.take` command didn't assign the issue to you because you edited your comment. If you're still interested in working on this issue, please follow these steps:

1. Write a new comment on the issue.
2. Include the keyword `.take` in your new comment.

Once you do this, the issue should be assigned to you, and you can start working on it.

Let me know if you need any further clarification!

**Comment by w3irdrobot** [comment]
i can pick it up if @aruokhai is unable to complete it.

**Comment by blackgirlbytes** [comment]
I'll reassign it to you since I know you just worked on the presentation definition part of the web5 cli so you may be familiar with this. @w3irdrobot 

@aruokhai I can help you find more related issues if you're interested!
