### ISSUE TITLE
Implement `mktemp` functionality in Web5 CLI

### ISSUE THREAD

**Issue by blackgirlbytes** [TBD54566975/web5-rs#387]
# Implement `mktemp` functionality in Web5 CLI

## 🚀 Goal
Add `mktemp` functionality to the Web5 Rust CLI to allow users to create temporary files and directories securely.

## 🔑 Tasks
- [ ] Research Rust's standard library capabilities for temporary file/directory creation
- [ ] Design the command structure (e.g., `web5 mktemp [OPTIONS]`)
- [ ] Implement core `mktemp` functionality:
  - [ ] Create temporary files
  - [ ] Create temporary directories
  - [ ] Allow user to specify prefix/suffix for temp names
  - [ ] Ensure proper permissions are set on created files/directories
- [ ] Add options for:
  - [ ] Dry-run mode (print name without creating)
  - [ ] Specifying alternative temp directory
  - [ ] Creating a specified number of temporary items
- [ ] Implement proper error handling and user feedback
- [ ] Ensure cross-platform compatibility (Unix-like systems and Windows)
- [ ] Write unit tests for the new functionality
- [ ] Update CLI documentation to include the new `mktemp` command
- [ ] Add examples of `mktemp` usage to the CLI help text

## 🌟 Resources
- [Rust tempfile crate](https://crates.io/crates/tempfile)
- [POSIX mktemp specification](https://pubs.opengroup.org/onlinepubs/9699919799/utilities/mktemp.html)
- [Rust standard library: std::env::temp_dir()](https://doc.rust-lang.org/std/env/fn.temp_dir.html)
- [Web5 CLI docs](https://developer.tbd.website/docs/web5/cli/)

## ⚡ Getting Started
1. Comment ".take" on this issue to get assigned
2. Fork the repository and create a new branch for this task
3. Implement the `mktemp` functionality
4. Write tests for your implementation
5. Update documentation and help text
6. Submit a pull request with your changes
7. Respond to any feedback during the review process

## Implementation Ideas
1. Consider using the `tempfile` crate for robust temporary file handling:

```rust
use tempfile::Builder;

let named_tempfile = Builder::new()
    .prefix("web5-")
    .suffix(".tmp")
    .rand_bytes(5)
    .tempfile()?;

println!("Created temporary file: {:?}", named_tempfile.path());
```

2. For cross-platform compatibility, use `std::env::temp_dir()` to get the system's temp directory:

```rust
use std::env;

let temp_dir = env::temp_dir();
println!("System temp directory: {:?}", temp_dir);
```

3. Implement a function to generate unique names:

```rust
use rand::{thread_rng, Rng};
use std::path::PathBuf;

fn generate_unique_name(prefix: &str, suffix: &str) -> PathBuf {
    let random_string: String = thread_rng()
        .sample_iter(&rand::distributions::Alphanumeric)
        .take(10)
        .map(char::from)
        .collect();
    
    PathBuf::from(format!("{}{}{}", prefix, random_string, suffix))
}
```

## 💭 Questions?
If you have any questions or need clarification, please comment on this issue or join our [Discord](https://discord.gg/tbd) community.

Happy coding! 🎉

**Comment by w3irdrobot** [comment]
before picking this up, i'm just curious what the use-case for this command being in this CLI is versus just using the unix `mktemp` command available via GNU `coreutils`?

**Comment by blackgirlbytes** [comment]
I'm going to ping @KendallWeihe to get his opinion on this! I made the issue based on a wish list he wrote but perhaps he can expand more on the goals!

**Comment by w3irdrobot** [comment]
@KendallWeihe is the idea of adding an output flag that it adds a consistent way that works on unix-based and windows systems for saving to a file since on linux saving to a file could just be done by redirecting stdout to a file?

**Comment by KendallWeihe** [comment]
> [@KendallWeihe](https://github.com/KendallWeihe) is the idea of adding an output flag that it adds a consistent way that works on unix-based and windows systems for saving to a file since on linux saving to a file could just be done by redirecting stdout to a file?

Great point honestly. And yeah I think there is some marginal value to providing a first-class feature for file creation instead of relying on the developer to use their native systems file concatenation syntax, but it's definitely marginal. IMO it's a nice feature to have but arguably not a super high priority.

**Comment by w3irdrobot** [comment]
well if it's still desired to work on, i can do the work. should take long at all.

**Comment by KendallWeihe** [comment]
> well if it's still desired to work on, i can do the work. shouldn't take long at all.

Yeah let's do it!
